### ISSUE TITLE
lesshint now distinguishes between errors and warnings

### ISSUE THREAD

**Issue by shellscape** [sagikazarmark/gulp-lesshint-stylish#1]
thanks for a nice little reporter. lesshint has been updated to provide distinction between errors and warnings. see https://github.com/lesshint/lesshint/pull/47

**Comment by sagikazarmark** [comment]
I guess you mean the severity should be indicated somewhere. Can you provide a PR?

**Comment by shellscape** [comment]
we're not currently using this reporter (we had to heavily modify it for our needs, and I do mean heavily - we're doing whacky stuff) so this was just more of a courtesy issue since I worked on the lesshint PR for that feature. cheers

**Comment by sagikazarmark** [comment]
@shellscape does #2 fix this issue?

**Comment by shellscape** [comment]
looks like it, thanks for the ping
